# Generated by Django 3.1.1 on 2020-09-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_manufac", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturer",
            name="country",
            field=models.IntegerField(
                choices=[
                    (1, "1"),
                    (91, "91"),
                    (93, "93"),
                    (48, "48"),
                    (86, "86"),
                    (33, "33"),
                    (81, "81"),
                    (51, "51"),
                    (92, "92"),
                    (7, "7"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(max_length=52),
        ),
    ]
